/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Clases.*;
import Controlador.*;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Familia
 */
public class Vista extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        mostrarPrimerInforme();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        informeComboBox = new javax.swing.JComboBox<>();
        btnMostrarInforme = new javax.swing.JButton();
        btnLimpiarInforme = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInforme = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PROYECTO CONSTRUCCIÓN - RETO 5 - DANIEL VELANDIA GONZÁLEZ");

        jLabel2.setText("Seleccione un informe:");

        informeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primer Informe", "Segundo Informe", "Tercer Informe" }));

        btnMostrarInforme.setText("Mostrar");
        btnMostrarInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarInformeActionPerformed(evt);
            }
        });

        btnLimpiarInforme.setText("Limpiar");
        btnLimpiarInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarInformeActionPerformed(evt);
            }
        });

        tablaInforme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaInforme);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(informeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrarInforme)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarInforme))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(informeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarInforme)
                    .addComponent(btnLimpiarInforme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarInformeActionPerformed
        // TODO add your handling code here:
        String informe = informeComboBox.getSelectedItem().toString();
        
        switch (informe) {
            case "Primer Informe" -> {mostrarPrimerInforme();}
            case "Segundo Informe" -> {mostrarSegundoInforme();}
            case "Tercer Informe" -> {mostrarTercerInforme();}
        }
    }//GEN-LAST:event_btnMostrarInformeActionPerformed

    private void btnLimpiarInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarInformeActionPerformed
        // TODO add your handling code here
        modelo.setRowCount(0);
        modelo.setColumnCount(0);
        informeComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarInformeActionPerformed

    
    public void mostrarPrimerInforme() {
        LinkedList<Lider> listLd = PrimerInformeCt.info();
        modelo = new DefaultTableModel();
        
        modelo.addColumn("ID Lider");
        modelo.addColumn("Nombre");
        modelo.addColumn("Primer Apellido");
        modelo.addColumn("Ciudad de Recidencia");
        tablaInforme.setModel(modelo);
        
        for (Lider ld : listLd) {
            String[] info = new String[4];
            
            info[0] = String.valueOf(ld.getId());
            info[1] = ld.getNombre();
            info[2] = ld.getPrimerApellido();
            info[3] = ld.getCiudadRecidencia();
            
            modelo.addRow(info);
        }
    }
    
    public void mostrarSegundoInforme() {
        LinkedList<Proyecto> listP = SegundoInformeCt.info();
        modelo = new DefaultTableModel();
        
        modelo.addColumn("ID_Lider");
        modelo.addColumn("constructora");
        modelo.addColumn("numero_habitaciones");
        modelo.addColumn("ciudad");
        tablaInforme.setModel(modelo);
        
        for (Proyecto p : listP) {
            String[] info = new String[4];
            
            info[0] = String.valueOf(p.getId());
            info[1] = p.getConstructora();
            info[2] = String.valueOf(p.getNumHab());
            info[3] = p.getCiudad();
            
            modelo.addRow(info);
        }
    }
    
    public void mostrarTercerInforme() {
        LinkedList<Compra> listC = TercerInformeCt.info();
        modelo = new DefaultTableModel();
        
        modelo.addColumn("ID_Compra");
        modelo.addColumn("constructora");
        modelo.addColumn("banco_vinculado");
        tablaInforme.setModel(modelo);
        
        for (Compra c : listC) {
            String[] info = new String[3];
            
            info[0] = String.valueOf(c.getId());
            info[1] = c.getConstructora();
            info[2] = c.getBanco();
            
            modelo.addRow(info);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiarInforme;
    private javax.swing.JButton btnMostrarInforme;
    private javax.swing.JComboBox<String> informeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaInforme;
    // End of variables declaration//GEN-END:variables
}
